# Generated by Django 3.1.6 on 2021-02-10 13:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_auto_20210210_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 10, 13, 31, 42, 196470, tzinfo=utc)),
        ),
    ]
