# Generated by Django 3.1.6 on 2021-02-10 13:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_otp_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 10, 13, 32, 25, 970999, tzinfo=utc)),
        ),
    ]
