# Generated by Django 3.1.6 on 2021-02-10 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_auto_20210210_1900'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otp',
            old_name='date',
            new_name='time',
        ),
        migrations.RemoveField(
            model_name='otp',
            name='expiry_date',
        ),
        migrations.AlterField(
            model_name='otp',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
