# Generated by Django 3.1.6 on 2021-02-10 07:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0007_auto_20210210_1301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otp',
            name='user',
        ),
        migrations.AlterField(
            model_name='otp',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 10, 7, 33, 56, 743380, tzinfo=utc)),
        ),
    ]
