# Generated by Django 3.1.6 on 2021-02-10 08:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0011_auto_20210210_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='expiry_date',
            field=models.DateTimeField(verbose_name=datetime.timedelta(seconds=120)),
        ),
    ]
